### PR TITLE
Allow nanonetcall to use networks trained on non-canonical alphabets

### PR DESCRIPTION
**Pull request by scottgigante**
Currently nanonettrain accepts alternative alphabets, but nanonetcall crashes if running on a network trained with this feature. 

Note that I have not made modifications to allow this feature in rapid mode.

### CODE REVIEW

**Comment by cjw85** [comment]
@scottgigante If you can remove the explicit dependence on the base identities (rather than simply the count of unique bases) I'll be happy to merge this. The identity and count are both calculable from the models' `kmers` field.

**Comment by scottgigante** [comment]
My apologies, this PR slipped to the back of my mind and I used this repo as an example for another user. I'll move the sample files to another branch and fix up the PR in due course.

**Comment by cjw85** [comment]
Sorry to be a pain, the opencl decoding kernel assumes 4 bases. I'm happy to accept throwing an exception `process_read_opencl` when more than 4 bases are present, and and early escape from nanonetcall (say at this block: https://github.com/nanoporetech/nanonet/blob/master/nanonet/nanonetcall.py#L475) when a user tries.

Thanks for the PR!

**Comment by scottgigante** [comment]
@cjw85, that should be all fixed. 

@mattloose, I've put some properly labelled files at https://github.com/scottgigante/nanonet/tree/dev/sample_data/labelled if you're interested.

**Comment by mattloose** [comment]
Thanks - that's cool. Was interested to see how you were labelling - and then puzzled when I couldn't see anything ;-)

**Comment by scottgigante** [comment]
@cjw85 not sure how to raise an exception on this in run() without prematurely loading the network file - it is otherwise only opened within ```process_read``` or ```process_read_cl```. I've added an exception into ```process_read_cl``` for now.

**Pull request merged**
